version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  create_infrastructure:
    # The primary container, where your job's commands will run
    docker:
    - image: amazon/aws-cli
    steps:
    - checkout # check out the code in the project directory
    - run:
        name: Create Cloudformation Stack
        command: "aws cloudformation deploy \\\n--template-file .circleci/template.yml \\\n--stack-name myStack"
        command: "aws cloudformation describe-stack-events --stack-name myStack"
    - run:
        name: Add IP to ansible Inventory
        command: |
          PUBLIC_IP=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=prometheus" \
          --query 'Reservations[*].Instances[*].PublicIpAddress' \
          --output text)
          echo $PUBLIC_IP >> .circleci/inventory.txt
          cat .circleci/inventory.txt
    - run:
        name: Add IP to ansible Inventory
        command: |
          PUBLIC_IP=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=node-exporter" \
          --query 'Reservations[*].Instances[*].PublicIpAddress' \
          --output text)
          echo $PUBLIC_IP >> .circleci/inventory.txt
          cat .circleci/inventory.txt

    - persist_to_workspace:
        root: ~/
        paths:
        - project/.circleci/inventory.txt
  configure_infrastructure:
    docker:
    - image: python:3.7-alpine3.11
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints: ["SHA256:H/wNS3ZyM2Vf+wQHD46toXq8lwSPyiqT2N+dcrwSteA"]
    - run:
        name: install dependencies
        command: "apt-get install sudo\nsudo apt update\nsudo apt install software-properties-common -y\nsudo add-apt-repository --yes --update ppa:ansible/ansible\nsudo apt install ansible -y \napk add --update ansible\n"
    - run:
        name: configure_server
        command: "ansible-playbook -i inventory.txt main.yml"
# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
    - create_infrastructure
    - configure_infrastructure


