- - -
- name: Update yum repo
  yum:
    name: "*"
    state: latest
- name: Create node_exporter user
  shell: "sudo useradd --no-create-home --shell /bin/false node_exporter \nsudo mkdir /etc/node_exporter sudo mkdir /var/lib/node_exporter \n"
- name: Download file from a path
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz/
    dest: /home/ubuntu/node_exporter-1.0.1.linux-amd64.tar.gz
- name: Extract tar
  unarchive:
    src: /home/ubuntu/node_exporter-1.0.1.linux-amd64.tar.gz
    dest: /home/ubuntu/
    remote_src: yes
- name: Move node_exporter
  shell: |
    sudo rm -rf node-files
    sudo mv /home/ubuntu/node_exporter-1.0.1.linux-amd64 node-files
- name: Move files
  shell: "sudo cp node-files/node_exporter /usr/local/bin/node_exporter\nsudo rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64 \n"
- name: Copy node.yaml
  become: true
  copy:
    src: node.yaml
    dest: /etc/node_exporter/
- name: Copy node-exporter.service
  become: true
  copy:
    src: node-exporter.service
    dest: /etc/systemd/system/
- name: Reload node_exporter to register changes
  shell: |
    sudo systemctl daemon-reload
    sudo systemctl enable node-exporter
    sudo systemctl start node-exporter
    sudo systemctl status node-exporter
